//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordKeep.Data.Entity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordKeep.Data.Entity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string FinTypeBank {
            get {
                return ResourceManager.GetString("FinTypeBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Loan.
        /// </summary>
        internal static string FinTypeCarLoan {
            get {
                return ResourceManager.GetString("FinTypeCarLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string FinTypeCreditCard {
            get {
                return ResourceManager.GetString("FinTypeCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Union.
        /// </summary>
        internal static string FinTypeCreditUnion {
            get {
                return ResourceManager.GetString("FinTypeCreditUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        internal static string FinTypeInsurance {
            get {
                return ResourceManager.GetString("FinTypeInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment.
        /// </summary>
        internal static string FinTypeInvestment {
            get {
                return ResourceManager.GetString("FinTypeInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage.
        /// </summary>
        internal static string FinTypeMortgage {
            get {
                return ResourceManager.GetString("FinTypeMortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Specified.
        /// </summary>
        internal static string FinTypeNotSpecified {
            get {
                return ResourceManager.GetString("FinTypeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string FinTypeOther {
            get {
                return ResourceManager.GetString("FinTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Loan.
        /// </summary>
        internal static string FinTypePersonalLoan {
            get {
                return ResourceManager.GetString("FinTypePersonalLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings and Loan.
        /// </summary>
        internal static string FinTypeSavingsAndLoan {
            get {
                return ResourceManager.GetString("FinTypeSavingsAndLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple.
        /// </summary>
        internal static string OfficialNameApple {
            get {
                return ResourceManager.GetString("OfficialNameApple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Provider.
        /// </summary>
        internal static string OfficialNameCustom {
            get {
                return ResourceManager.GetString("OfficialNameCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string OfficialNameFacebook {
            get {
                return ResourceManager.GetString("OfficialNameFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        internal static string OfficialNameGoogle {
            get {
                return ResourceManager.GetString("OfficialNameGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        internal static string OfficialNameMicrosoft {
            get {
                return ResourceManager.GetString("OfficialNameMicrosoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None Specified.
        /// </summary>
        internal static string OfficialNameNone {
            get {
                return ResourceManager.GetString("OfficialNameNone", resourceCulture);
            }
        }
    }
}
